# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.quit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.quit_btn.setGeometry(QtCore.QRect(890, 580, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_btn.sizePolicy().hasHeightForWidth())
        self.quit_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("苹方")
        font.setPointSize(14)
        self.quit_btn.setFont(font)
        self.quit_btn.setObjectName("quit_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 191, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("苹方")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 20, 321, 34))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 100, 72, 22))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 100, 72, 22))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 90, 91, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("苹方")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_month = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_month.setGeometry(QtCore.QRect(280, 90, 61, 34))
        self.lineEdit_month.setObjectName("lineEdit_month")
        self.lineEdit_year = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_year.setGeometry(QtCore.QRect(180, 90, 61, 34))
        self.lineEdit_year.setObjectName("lineEdit_year")
        self.lineEdit_datemask = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_datemask.setGeometry(QtCore.QRect(160, 190, 321, 34))
        self.lineEdit_datemask.setObjectName("lineEdit_datemask")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 150, 271, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("苹方")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_pwd = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pwd.setGeometry(QtCore.QRect(150, 250, 321, 34))
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 250, 91, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("苹方")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(70, 390, 391, 161))
        self.textEdit.setObjectName("textEdit")
        self.quit_btn_rstquery = QtWidgets.QPushButton(self.centralwidget)
        self.quit_btn_rstquery.setGeometry(QtCore.QRect(110, 580, 161, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_btn_rstquery.sizePolicy().hasHeightForWidth())
        self.quit_btn_rstquery.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("苹方")
        font.setPointSize(14)
        self.quit_btn_rstquery.setFont(font)
        self.quit_btn_rstquery.setObjectName("quit_btn_rstquery")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(70, 330, 51, 27))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(160, 330, 51, 27))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(230, 290, 120, 111))
        self.groupBox.setObjectName("groupBox")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(0, 70, 105, 27))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_1 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_1.setGeometry(QtCore.QRect(0, 20, 105, 27))
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(0, 40, 105, 40))
        self.checkBox_2.setObjectName("checkBox_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(540, 90, 351, 30))
        self.comboBox.setObjectName("comboBox")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(540, 60, 351, 22))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 610, 891, 51))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.quit_btn_rstquery_2 = QtWidgets.QPushButton(self.centralwidget)
        self.quit_btn_rstquery_2.setGeometry(QtCore.QRect(750, 580, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_btn_rstquery_2.sizePolicy().hasHeightForWidth())
        self.quit_btn_rstquery_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("苹方")
        font.setPointSize(14)
        self.quit_btn_rstquery_2.setFont(font)
        self.quit_btn_rstquery_2.setObjectName("quit_btn_rstquery_2")
        self.quit_btn_rstquery_3 = QtWidgets.QPushButton(self.centralwidget)
        self.quit_btn_rstquery_3.setGeometry(QtCore.QRect(540, 20, 161, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_btn_rstquery_3.sizePolicy().hasHeightForWidth())
        self.quit_btn_rstquery_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("苹方")
        font.setPointSize(14)
        self.quit_btn_rstquery_3.setFont(font)
        self.quit_btn_rstquery_3.setObjectName("quit_btn_rstquery_3")
        self.quit_btn_rstquery_4 = QtWidgets.QPushButton(self.centralwidget)
        self.quit_btn_rstquery_4.setGeometry(QtCore.QRect(530, 180, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_btn_rstquery_4.sizePolicy().hasHeightForWidth())
        self.quit_btn_rstquery_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("苹方")
        font.setPointSize(14)
        self.quit_btn_rstquery_4.setFont(font)
        self.quit_btn_rstquery_4.setObjectName("quit_btn_rstquery_4")
        self.quit_btn_rstquery_5 = QtWidgets.QPushButton(self.centralwidget)
        self.quit_btn_rstquery_5.setGeometry(QtCore.QRect(770, 180, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_btn_rstquery_5.sizePolicy().hasHeightForWidth())
        self.quit_btn_rstquery_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("苹方")
        font.setPointSize(14)
        self.quit_btn_rstquery_5.setFont(font)
        self.quit_btn_rstquery_5.setObjectName("quit_btn_rstquery_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(530, 130, 381, 41))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.quit_btn_rstquery_6 = QtWidgets.QPushButton(self.centralwidget)
        self.quit_btn_rstquery_6.setGeometry(QtCore.QRect(650, 180, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_btn_rstquery_6.sizePolicy().hasHeightForWidth())
        self.quit_btn_rstquery_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("苹方")
        font.setPointSize(14)
        self.quit_btn_rstquery_6.setFont(font)
        self.quit_btn_rstquery_6.setObjectName("quit_btn_rstquery_6")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(540, 350, 392, 214))
        self.calendarWidget.setObjectName("calendarWidget")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(530, 250, 371, 51))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 28))
        self.menubar.setObjectName("menubar")
        self.menuAsd = QtWidgets.QMenu(self.menubar)
        self.menuAsd.setObjectName("menuAsd")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionA = QtWidgets.QAction(MainWindow)
        self.actionA.setObjectName("actionA")
        self.actionB = QtWidgets.QAction(MainWindow)
        self.actionB.setObjectName("actionB")
        self.action_showpic = QtWidgets.QAction(MainWindow)
        self.action_showpic.setObjectName("action_showpic")
        self.action_showtab = QtWidgets.QAction(MainWindow)
        self.action_showtab.setObjectName("action_showtab")
        self.menuAsd.addSeparator()
        self.menuAsd.addSeparator()
        self.menuAsd.addAction(self.actionA)
        self.menuAsd.addAction(self.actionB)
        self.menubar.addAction(self.menuAsd.menuAction())
        self.toolBar.addAction(self.action_showpic)
        self.toolBar.addAction(self.action_showtab)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.quit_btn.setText(_translate("MainWindow", "退出"))
        self.label.setText(_translate("MainWindow", "建模协会制～"))
        self.label_2.setText(_translate("MainWindow", "年"))
        self.label_3.setText(_translate("MainWindow", "月"))
        self.label_4.setText(_translate("MainWindow", "参赛时间"))
        self.label_5.setText(_translate("MainWindow", "输入年月日：如2016-09-18"))
        self.label_6.setText(_translate("MainWindow", "输入密码"))
        self.quit_btn_rstquery.setText(_translate("MainWindow", "显示查询"))
        self.radioButton.setText(_translate("MainWindow", "男"))
        self.radioButton_2.setText(_translate("MainWindow", "女"))
        self.groupBox.setTitle(_translate("MainWindow", "复选框"))
        self.checkBox_3.setText(_translate("MainWindow", "3"))
        self.checkBox_1.setText(_translate("MainWindow", "国家级"))
        self.checkBox_2.setText(_translate("MainWindow", "2"))
        self.quit_btn_rstquery_2.setText(_translate("MainWindow", "完成"))
        self.quit_btn_rstquery_3.setText(_translate("MainWindow", "获得比赛选项"))
        self.quit_btn_rstquery_4.setText(_translate("MainWindow", "导入文件"))
        self.quit_btn_rstquery_5.setText(_translate("MainWindow", "打开图片"))
        self.quit_btn_rstquery_6.setText(_translate("MainWindow", "保存文件"))
        self.menuAsd.setTitle(_translate("MainWindow", "文件"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionA.setText(_translate("MainWindow", "导入文件"))
        self.actionB.setText(_translate("MainWindow", "导出文件"))
        self.action_showpic.setText(_translate("MainWindow", "绘图展示"))
        self.action_showpic.setToolTip(_translate("MainWindow", "绘图展示"))
        self.action_showtab.setText(_translate("MainWindow", "表格展示"))
        self.action_showtab.setToolTip(_translate("MainWindow", "表格展示"))
